import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { RootSidebar } from '@/containers/Sidebar/RootSidebar'
import { Transaction } from '@/containers/DashModule/Transaction'
import { Users } from '@/containers/DashModule/Users'
import Link from 'next/link'
import House from '../containers/DashModule/House/index'
import HouseTest from './HouseTest'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RootSidebar />
        <div>
          <Link href='/HouseTest'>
            Router Test
          </Link>
        </div>
      </main>
    </>
  )
}
